basePath: /api
definitions:
  models.GenreRequest:
    properties:
      name:
        type: string
    type: object
  models.Response:
    properties:
      Data: {}
      Message:
        type: string
      Status:
        type: string
    type: object
  models.UserRequest:
    properties:
      lastname:
        type: string
      surname:
        type: string
    type: object
info:
  contact: {}
  description: 'A simple API to manage movie rentals \n GitHub Repository: https://github.com/jorgemvv01/go-api'
  title: VideoClub Go - REST API
  version: "1.0"
paths:
  /genres:
    get:
      description: Get all Genres.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get all Genres
      tags:
      - Movie Genre
  /genres/{ID}:
    get:
      description: Get a genre by ID.
      parameters:
      - description: Get genre by ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Genre by ID
      tags:
      - Movie Genre
  /genres/create:
    post:
      description: Create a new genre.
      parameters:
      - description: Create genre
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/models.GenreRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create Genre
      tags:
      - Movie Genre
  /genres/delete/{ID}:
    delete:
      description: Delete Genre by ID.
      parameters:
      - description: Delete genre by ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Delete Genre
      tags:
      - Movie Genre
  /genres/update/{ID}:
    patch:
      description: Update Genre by ID.
      parameters:
      - description: Update genre by ID
        in: path
        name: ID
        required: true
        type: string
      - description: Create genre
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/models.GenreRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Update Genre
      tags:
      - Movie Genre
  /types/:
    get:
      description: Get all Types
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get all Types
      tags:
      - Movie Type
  /types/{ID}:
    get:
      description: Get Type by ID
      parameters:
      - description: Get Type by ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get Type by ID
      tags:
      - Movie Type
  /users:
    get:
      description: Get all Users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get all Users
      tags:
      - Users
  /users/{ID}:
    get:
      description: Get a user by ID.
      parameters:
      - description: Get user by ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get User by ID
      tags:
      - Users
  /users/create:
    post:
      description: Create a new user.
      parameters:
      - description: Create user
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create User
      tags:
      - Users
  /users/delete/{ID}:
    delete:
      description: Delete User by ID.
      parameters:
      - description: Delete user by ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Delete User
      tags:
      - Users
  /users/update/{ID}:
    patch:
      description: Update User by ID.
      parameters:
      - description: Update user by ID
        in: path
        name: ID
        required: true
        type: string
      - description: Create user
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Response'
      summary: Update User
      tags:
      - Users
swagger: "2.0"
