basePath: /api
definitions:
  models.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  models.UserRequest:
    properties:
      lastname:
        type: string
      surname:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A simple API to manage movie rentals
  title: VideoClub GO-API
  version: "1.0"
paths:
  /users:
    get:
      description: Get all Users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/models.Response'
            type: array
      summary: Get all Users
      tags:
      - Users
  /users/{ID}:
    get:
      description: Get a user by ID.
      parameters:
      - description: Get user by ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: Get User by ID
      tags:
      - Users
  /users/create:
    post:
      description: Create a new user.
      parameters:
      - description: Create user
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create User
      tags:
      - Users
swagger: "2.0"
